# Generated by Django 3.2.6 on 2021-08-17 22:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_fsm_enhanced.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('state', django_fsm_enhanced.fields.EnhancedFSMField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('content', models.TextField(blank=True, default='')),
                ('state', django_fsm_enhanced.fields.EnhancedFSMField(choices=[('DRAFT', 'Draft'), ('PUBLIC', 'Public'), ('PRIVATE', 'Private'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=50)),
                ('authors', models.ManyToManyField(related_name='posts', to='blog.BlogAuthor')),
            ],
        ),
        migrations.CreateModel(
            name='BlogPostStateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_state', models.CharField(blank=True, db_index=True, default=None, max_length=255, null=True, verbose_name='Source state')),
                ('state', models.CharField(db_index=True, max_length=255, verbose_name='Target state')),
                ('transition', models.CharField(db_index=True, max_length=255, verbose_name='Transition name')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('meta_data', models.JSONField(default=dict)),
                ('by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_logs', to='blog.blogpost')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BlogAuthorStateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_state', models.CharField(blank=True, db_index=True, default=None, max_length=255, null=True, verbose_name='Source state')),
                ('state', models.CharField(db_index=True, max_length=255, verbose_name='Target state')),
                ('transition', models.CharField(db_index=True, max_length=255, verbose_name='Transition name')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('meta_data', models.JSONField(default=dict)),
                ('by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_logs', to='blog.blogauthor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
